name: words_numbers
description: WordsNumbers is a Flutter plugin that helps convert text numbers to their corresponding numeric values.
version: 0.0.4
homepage: https://github.com/arsarsars1/words_numbers.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
