name: words_numbers
description: WordsNumbers is a Flutter plugin that helps convert text numbers to their corresponding numeric values.
version: 0.0.2
homepage: https://github.com/arsarsars1/words_numbers.git

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
